server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.28.5.43:3100/loki/api/v1/push

scrape_configs:
  - job_name: journald
    journal:
      max_age: 6h
      path: /var/log/journal
      labels:
        job: systemd-journal
        hostname: monitor
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label: systemd_unit
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - action: replace
        source_labels: [__meta_docker_container_log_path]
        target_label: __path__
        regex: '/var/lib/docker/containers/(.*)/(.*)-json.log'
        replacement: '/var/lib/docker/containers/$1/$2-json.log'
